[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[providers.kubernetesCRD]
[providers.kubernetesIngress]

[api]
  dashboard = true
  # insecure = true

[serversTransport]
  insecureSkipVerify = true
