{
 "title": "Wintergatan Discord",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "content": "<img src=\"https://cdn.shopify.com/s/files/1/0473/6097/files/NEW_SHOPIFY_LOGO_V1_1300x.png?v=1583671990\" />"
  },
  {
   "title": "Members online",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(discord_members_presence_total{presence!=\"offline\"})"
    }
   ]
  },
  {
   "title": "Total members",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "discord_members_total" }
   ]
  },
  {
   "title": "Members online",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discord_members_presence_total{presence!~\"(deleted|offline)\"}",
     "legendFormat": "{{presence}}"
    }
   ]
  },
  {
   "title": "Total members",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "discord_members_total", "legendFormat": "Members" }
   ]
  },
  {
   "title": "Human messages sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "discord_messages_sent_total{bot=\"false\"}",
     "legendFormat": "Sent {{channel}}"
    },
    {
     "expr": "-discord_messages_deleted_total",
     "legendFormat": "Deleted {{channel}}"
    },
    { "expr": "-discord_messages_edited_total", "legendFormat": "Edited {{channel}}" }
   ]
  },
  {
   "title": "Games",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "discord_members_games_total{game!~\"(|Spotify|Custom Status)\"} > 2",
     "legendFormat": "{{game}}"
    }
   ]
  },
  {
   "title": "Total messages sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(discord_messages_sent_total)",
     "legendFormat": "Total messages sent"
    }
   ]
  },
  {
   "title": "Incoming events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "discord_events_received_total", "legendFormat": "{{event}}" }
   ]
  }
 ]
}